added a filter to general timeline
HadarRose/onboarding-ui pull request #12
Opened 2020-09-11 17:54 UTC by HadarRose

2020-09-11 19:08 UTC, kev-chan requested changes
Refresh button should be left aligned for the general timeline

2020-09-11 19:08 UTC, kev-chan commented on src/js/components/timeline.js
> +        this.setState({keyword: ''}); // clear filter
don't clear the filter on the get.

2020-09-11 19:16 UTC, HadarRose commented on src/js/components/timeline.js
> +        this.setState({keyword: ''}); // clear filter
updated

2020-09-16 13:50 UTC, kev-chan approved these changes

2020-09-17 17:01 UTC, merged