S101 webpack
HadarRose/onboarding-ui pull request #5
Opened 2020-08-24 16:01 UTC by HadarRose

Added webpack to project. Includes creating /dist folder for distribution files, package.json, webpack.config.js, and updating the README file

2020-08-24 16:18 UTC, kev-chan requested changes

2020-08-24 16:18 UTC, kev-chan commented on src/js/basicRequests.js
> +getTimeline = function() {
don't use global scope

2020-08-24 16:19 UTC, kev-chan commented on src/js/basicRequests.js
> +getTimeline = function() {
global scope should only be used when absolutely needed

2020-08-24 16:19 UTC, kev-chan commented
looks like you've still got old commits on this branch compared to master

2020-08-24 16:20 UTC, HadarRose commented
@kev-chan I just saw that I indeed forgot to merge the old PR. Will take care of that now

2020-08-24 20:11 UTC, kev-chan commented on src/js/main.js
> +    document.getElementById("main-container").onload = getTimeline();
is attaching it to the onload needed?

2020-08-24 20:17 UTC, HadarRose commented on src/js/main.js
> +    document.getElementById("main-container").onload = getTimeline();
Didn't think about that! just pushed a fix

2020-08-25 13:46 UTC, kev-chan commented
The old commits should not be showing up in this PR and should only contain webpack relevant changes.  Please fix

2020-08-25 16:12 UTC, kev-chan approved these changes

2020-08-25 16:13 UTC, merged