S102 scss
HadarRose/onboarding-ui pull request #6
Opened 2020-08-25 16:54 UTC by HadarRose

Converted CSS to SCSS

2020-08-25 17:59 UTC, kev-chan requested changes
since you're using scss you should be able to make all of your rules more specific

2020-08-25 18:41 UTC, HadarRose commented
@kev-chan I pushed an improvement of the nesting, but I'm not sure that would be considered more specific per se. Could you expand on what you mean by more specific rules?

2020-08-26 14:00 UTC, kev-chan commented
what does scss do with the scss rules you write?  think about this and how that would impact a large scale project in terms of classes and more specific rules could help

2020-08-26 15:46 UTC, kev-chan approved these changes

2020-08-26 15:55 UTC, merged