Converted to React
HadarRose/onboarding-ui pull request #8
Opened 2020-08-27 19:01 UTC by HadarRose

replaced basicRequests.js with multiple React components

2020-08-28 19:17 UTC, kev-chan requested changes

2020-08-28 19:17 UTC, kev-chan commented on src/js/timeline.js
> +                <div className="timeline-container">
timeline-container is still duplicated

2020-08-28 19:17 UTC, kev-chan commented on src/js/timelineService.js
> +export default class TimelineService{
how re-usable is this class?

2020-08-28 19:35 UTC, HadarRose commented
@kev-chan I pushed a new version. Took care of the duplication, and made it so that the service calls "timeline.updateState" instead, which means it could be used by any class with an updateState method in the way that updateState is implemented. (as opposed to setting the state from the service, since different callers may have different states)

2020-08-31 14:52 UTC, kev-chan requested changes

2020-08-31 14:52 UTC, kev-chan commented on src/js/timelinePage.js
> +                <div className="timeline-container">
are you expecting this to be part of timeline if someone else was to just render `<Timeline ...>?

2020-08-31 14:52 UTC, kev-chan commented on src/js/timelineService.js
> +export default class TimelineService{
update to use function

2020-08-31 18:22 UTC, kev-chan commented on src/js/timelineService.js
> +    constructor(func){
call it `callback` rather than func.  It's the actual technical term for it

2020-08-31 18:30 UTC, merged